### ISSUE TITLE
Spanning multiple lines

### ISSUE THREAD

**Issue by us** [what-the-func/func-wallet#1]
![screen shot on nov 10th at 02-11 am](https://user-images.githubusercontent.com/22618852/32634398-1e06bf4a-c5b4-11e7-831b-b5d9f5849ea6.png)
I often get this error.Why? Because of version ? or ?

```browser/SafeMath.sol:8:3: Warning: Function state mutability can be restricted to pure
  function mul(uint256 a, uint256 b) internal returns (uint256) {
  ^
Spanning multiple lines.```

**Comment by ezynda3** [comment]
It's just a warning that those functions will default to "public". If you add public to the scope the warnings will go away.
